### ISSUE TITLE
Power Workflows

### ISSUE THREAD

**Issue by gyoung41** [pgorod/pgorod.github.io#1]
Hi - I set up a sponsorship to download Power Workflows but can't seem to be able to access it.

**Comment by pgorod** [comment]
Hey there, welcome! 

It's a manual step, I just added you to a private repository. You should receive an email invite.

Thanks a lot for the generous Sponsorship 🎉 

Do you have an account in the SuiteCRM forums? If you can send me a Private message there, it's the best way for us to be in contact, in private: https://community.suitecrm.com/u/pgr/

**Comment by pgorod** [comment]
Hi @gyoung41 

I noticed you gave up on the Sponsorship. Can you give me some feedback on what happened. Did you ever get to install the add-on? Did it work for you?

I'm always looking for ways to improve and your feedback would be quite valuable. Thanks!

**Comment by gyoung41** [comment]
Hi

Our system is quite heavily customised and when we installed power workflows we started experiencing issues. Also it didn't do what we need so we uninstalled it.

Regards
Gavin

**Comment by pgorod** [comment]
Ok, fair enough.

If you can get me some technical information on the issues you experienced, I would be grateful, this software is in its initial stages, there's probably things to improve. But I also understand if it's too fuzzy or too much work for you to get this for me.

I would also appreciate ideas for new features: you mention it "didn't do what we need", maybe I can add that to the add-on?

I hope I'm not being too annoying with these requests, and I'm not necessarily trying to get you back into the Sponsorship, I'd be happy to just get some actionable bug reports / feature requests.

Cheers!
