### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by pgorod** [pgorod/pgorod.github.io#2]
Hi @bbill (I hope you get a notification from this mention...)

Did you get an email from Github with an invitation to join a private repo? That was from me, it's the only way I can contact you in private. if you can please accept that invitation we can continue this conversation there. 

Thanks!

**Comment by bbill** [comment]
Just notice it when you close this issue ：）。

**Comment by pgorod** [comment]
Oh! Wow. 
Well, thank you for your sponsorship even though it was only for a short time 🎉 

I'm curious, what's your story with SuiteCRM? Are you still using it?

**Comment by bbill** [comment]
pgorod,

I am not familiar with the sponsor rule. And take it as sth pay for the new
feature. and I don't got this feature(tag or sth). So I stop the
sponsorship.

But I still use suitecrm to help manage our customers. And I do appreciate
it.
I  modify some code to support pdf in Chinese. But it does lack some
important features these day. like cowork with social media.

BTW.

If you are interested, maybe we can cowork on sth bigger.




pgorod ***@***.***> 于2024年11月15日周五 06:00写道：
